### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by sorincocorada** [chomupashchuk/ariston-remotethermo-api#6]
Thanks for the wonderful work, I have used the library until yesterday, but starting from today morning it seem that it doesn't work anymore. I suspect they have made some changes to the API, because at least in the WebUI there are more menus.

**Comment by chomupashchuk** [comment]
yes, there are multiple changes and I'm still trying to adapt the code to new rest requests.

**Comment by chomupashchuk** [comment]
try new version
